name: ${project.name}
main: me.cyberfla.reclaim.Main
version: ${project.version}
commands:
  reclaim:
    description: Reclaim main player command
  claim:
    description: Reclaim plugin root command
  resetreclaim:
    description: Reset player reclaims!
