Broadcast: true
Message: '&b{PLAYER} &7has reclaimed their &e{GROUP} rank rewards!'
Reclaim:
  groups:
    VIP:
      - eco give {PLAYER} 10000
    Donator:
      - eco give {PLAYER} 25000
    Mortal:
      - eco give {PLAYER} 50000
    WarLord:
      - eco give {PLAYER} 75000
    Chosen:
      - eco give {PLAYER} 100000
  redeemedPlayers:
    VIP:
    Donator:
    Mortal:
    WarLord:
    Chosen:
